name: pinkmonkey
favicon: null
layout_spectrum: 0.624154215445742
typography_spectrum: 0.09420822351239622
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6324985306710005
  lightness: 0.5537720662541687
  saturation: 0.25160229625180364
  rhythmicContrast: 0.6809231203515083
purpose: []
