name: pinkmonkey
favicon: null
layout_spectrum: 0.23429
typography_spectrum: 0.28429
title: Pink Monkey Project
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fc8f99'
    - '#fc757e'
    - '#fcb5ba'
    - '#fdd9dd'
  brandStrength: 0.625
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
